package gameoflife;

/**
 *most of this is auto generated by Netbeans IDE  
 */
public class SettingDialog extends javax.swing.JFrame {

    public SettingDialog() {
        initComponents();
        for (Rule rule : GameOfLife.rules) {
            rules.addItem(rule);
        }
        edged.setSelected(GameOfLife.gameBoard.getScales().isEdged());
        heightTXT.setText("" + GameOfLife.gameBoard.getScales().getHeight());
        widthTXT.setText("" + GameOfLife.gameBoard.getScales().getWidth());
        refreshCheckBox();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rulePanel = new javax.swing.JPanel();
        SRPanel = new javax.swing.JPanel();
        s0 = new javax.swing.JCheckBox();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        CRPanel = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c0 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        rules = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        setRuleBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lh = new javax.swing.JLabel();
        edged = new javax.swing.JCheckBox();
        widthTXT = new javax.swing.JTextField();
        heightTXT = new javax.swing.JTextField();

        setTitle("setting");

        rulePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        SRPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });

        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        s6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });

        s5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });

        s7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        s4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        s8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        javax.swing.GroupLayout SRPanelLayout = new javax.swing.GroupLayout(SRPanel);
        SRPanel.setLayout(SRPanelLayout);
        SRPanelLayout.setHorizontalGroup(
            SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s0)
                .addGap(18, 18, 18)
                .addComponent(s1)
                .addGap(18, 18, 18)
                .addComponent(s2)
                .addGap(20, 20, 20)
                .addComponent(s3)
                .addGap(18, 18, 18)
                .addComponent(s4)
                .addGap(18, 18, 18)
                .addComponent(s5)
                .addGap(18, 18, 18)
                .addComponent(s6)
                .addGap(18, 18, 18)
                .addComponent(s7)
                .addGap(18, 18, 18)
                .addComponent(s8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SRPanelLayout.setVerticalGroup(
            SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SRPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s5)
                    .addComponent(s8)
                    .addComponent(s4)
                    .addComponent(s7)
                    .addComponent(s3)
                    .addComponent(s6)
                    .addComponent(s2)
                    .addComponent(s1)
                    .addComponent(s0))
                .addContainerGap())
        );

        CRPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        c0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                survivalRuleChanged(evt);
            }
        });
        c0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleChanged(evt);
            }
        });

        javax.swing.GroupLayout CRPanelLayout = new javax.swing.GroupLayout(CRPanel);
        CRPanel.setLayout(CRPanelLayout);
        CRPanelLayout.setHorizontalGroup(
            CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c0)
                .addGap(18, 18, 18)
                .addComponent(c1)
                .addGap(18, 18, 18)
                .addComponent(c2)
                .addGap(18, 18, 18)
                .addComponent(c3)
                .addGap(20, 20, 20)
                .addComponent(c4)
                .addGap(18, 18, 18)
                .addComponent(c5)
                .addGap(18, 18, 18)
                .addComponent(c6)
                .addGap(18, 18, 18)
                .addComponent(c7)
                .addGap(18, 18, 18)
                .addComponent(c8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CRPanelLayout.setVerticalGroup(
            CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c0)
                    .addComponent(c6)
                    .addComponent(c5)
                    .addComponent(c8)
                    .addComponent(c4)
                    .addComponent(c7)
                    .addComponent(c3)
                    .addComponent(c2)
                    .addComponent(c1))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel1.setText("Ceation rule");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Survival rule");

        setRuleBTN.setText("Set Rule");
        setRuleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRuleBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("5");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("6");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("7");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("8");

        javax.swing.GroupLayout rulePanelLayout = new javax.swing.GroupLayout(rulePanel);
        rulePanel.setLayout(rulePanelLayout);
        rulePanelLayout.setHorizontalGroup(
            rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(setRuleBTN)
                        .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rulePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6))
                            .addGroup(rulePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rules, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rulePanelLayout.setVerticalGroup(
            rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setRuleBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SRPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("width:");

        lh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lh.setText("height:");

        edged.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edged.setText("edged");
        edged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgedActionPerformed(evt);
            }
        });

        widthTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTXTActionPerformed(evt);
            }
        });

        heightTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heightTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(widthTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edged))
                    .addComponent(rulePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edged)
                    .addComponent(widthTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lh)
                    .addComponent(heightTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruleChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleChanged

    }//GEN-LAST:event_ruleChanged

    private void setRuleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRuleBTNActionPerformed
        GameOfLife.gameBoard.setRule((Rule) rules.getSelectedItem());
        refreshCheckBox();
    }//GEN-LAST:event_setRuleBTNActionPerformed

    private void survivalRuleChanged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_survivalRuleChanged
        if (!(GameOfLife.gameBoard.getRule() instanceof NormalRule)) {
            return;
        }
        GameOfLife.gameBoard.setRule(GameOfLife.rules.get(GameOfLife.rules.size() - 1));
        rules.setSelectedIndex((GameOfLife.rules.size() - 1));
        NormalRule nr = (NormalRule) GameOfLife.rules.get(GameOfLife.rules.size() - 1);
        nr.getSurvivalRule()[0] = s0.isSelected();
        nr.getSurvivalRule()[1] = s1.isSelected();
        nr.getSurvivalRule()[2] = s2.isSelected();
        nr.getSurvivalRule()[3] = s3.isSelected();
        nr.getSurvivalRule()[4] = s4.isSelected();
        nr.getSurvivalRule()[5] = s5.isSelected();
        nr.getSurvivalRule()[6] = s6.isSelected();
        nr.getSurvivalRule()[7] = s7.isSelected();
        nr.getSurvivalRule()[8] = s8.isSelected();
        nr.getCreatRule()[0] = c0.isSelected();
        nr.getCreatRule()[1] = c1.isSelected();
        nr.getCreatRule()[2] = c2.isSelected();
        nr.getCreatRule()[3] = c3.isSelected();
        nr.getCreatRule()[4] = c4.isSelected();
        nr.getCreatRule()[5] = c5.isSelected();
        nr.getCreatRule()[6] = c6.isSelected();
        nr.getCreatRule()[7] = c7.isSelected();
        nr.getCreatRule()[8] = c8.isSelected();
    }//GEN-LAST:event_survivalRuleChanged

    private void edgedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgedActionPerformed
        GameOfLife.gameBoard.getScales().setEdged(edged.isSelected());
    }//GEN-LAST:event_edgedActionPerformed

    private void widthTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTXTActionPerformed
        try {
            int n = Integer.valueOf(widthTXT.getText());
            if (n >= 8 && n <= 50 && n != GameOfLife.gameBoard.getScales().getWidth()) {
                Scales newscales = new Scales(n, GameOfLife.gameBoard.getScales().getHeight());
                GameOfLife.gameBoard.setScales(newscales);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
            GameOfLife.gameFrame.refreshGamePanel();

    }//GEN-LAST:event_widthTXTActionPerformed

    private void heightTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTXTActionPerformed
        try {
            int n = Integer.valueOf(heightTXT.getText());
            if (n >= 8 && n <= 50 && n != GameOfLife.gameBoard.getScales().getHeight()) {
                Scales newscales = new Scales( GameOfLife.gameBoard.getScales().getWidth(),n);
                GameOfLife.gameBoard.setScales(newscales);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        GameOfLife.gameFrame.refreshGamePanel();
    }//GEN-LAST:event_heightTXTActionPerformed
    public void refreshCheckBox() {
        if (!(GameOfLife.gameBoard.getRule() instanceof NormalRule)) {
            return;
        }
        NormalRule nr = (NormalRule) GameOfLife.gameBoard.getRule();
        s0.setSelected(nr.getSurvivalRule()[0]);
        s1.setSelected(nr.getSurvivalRule()[1]);
        s2.setSelected(nr.getSurvivalRule()[2]);
        s3.setSelected(nr.getSurvivalRule()[3]);
        s4.setSelected(nr.getSurvivalRule()[4]);
        s5.setSelected(nr.getSurvivalRule()[5]);
        s6.setSelected(nr.getSurvivalRule()[6]);
        s7.setSelected(nr.getSurvivalRule()[7]);
        s8.setSelected(nr.getSurvivalRule()[8]);
        c0.setSelected(nr.getCreatRule()[0]);
        c1.setSelected(nr.getCreatRule()[1]);
        c2.setSelected(nr.getCreatRule()[2]);
        c3.setSelected(nr.getCreatRule()[3]);
        c4.setSelected(nr.getCreatRule()[4]);
        c5.setSelected(nr.getCreatRule()[5]);
        c6.setSelected(nr.getCreatRule()[6]);
        c7.setSelected(nr.getCreatRule()[7]);
        c8.setSelected(nr.getCreatRule()[8]);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CRPanel;
    private javax.swing.JPanel SRPanel;
    private javax.swing.JCheckBox c0;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox edged;
    private javax.swing.JTextField heightTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lh;
    private javax.swing.JPanel rulePanel;
    private javax.swing.JComboBox<Rule> rules;
    private javax.swing.JCheckBox s0;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.JButton setRuleBTN;
    private javax.swing.JTextField widthTXT;
    // End of variables declaration//GEN-END:variables
}
